In [6]:
text = """2.1 CNN의 구조 및 학습
CNN은 그림 1과 같이 크게 convolution-pooling layer
와 fully connected layer의 두 부분으로 구성되어 있
다. 전자는 입력된 이미지로부터 계층적 구조의
feature를 추출하는 역할을, 후자는 추출된 feature를
입력받아 타겟 클래스로 분류하는 역할을 담당한다.
CNN layer는 아래와 같은 두 가지 특징을 통해 이
미지 데이터의 특성을 반영하는 동시에 모델의 복잡
도를 크게 단순화시킨다.
1) Local connectivity: 가장 일반적인 형태인 fully
connected layer와 달리, 해당 convolution 필터의 크기
인 NxN window 내의 인접한 뉴런들에만 연결이 되
어있다. 이는 인접한 픽셀들끼리는 상관관계가 높지
만 멀리 떨어진 픽셀들은 그렇지 않은 이미지의 특성
특집원고
인천대학교 | IP:117.16.225.*** | Accessed 2021/01/11 23:04(KST)
26 특집원고 다양한 딥러닝 알고리즘과 활용
(a) (b) (c)
그림 2 자동차 이미지로 학습시킨 CNN의 (a) 하위 layer, (b) 중위 layer, (c) 상위 layer에서 학습한 feature [5]
(a) (b) (c)
그림 3 CNN을 이용한 네이버의 서비스. (a) N드라이브 사진 검색 (b) 지식iN 사진 질문 기반 디렉토리 추천 (c) 이미지 기반
라인 신규 스티커 추천
(locality)을 반영한 것이다.
2) Shared weights: convolution 필터들은 적용되는
위치가 달라도 같은 weight값을 공유한다. 이는 픽셀
값의 통계적 특성이 이미지 상의 좌표와 무관하다는
이미지의 특성(stationarity)을 반영한 것이다"""

In [7]:
from keras_preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts([text])
encoded = t.texts_to_sequences([text])[0]

In [8]:
vocab_size = len(t.word_index)+1

print('단어 집합의 크기: %d' % vocab_size)

print(t.word_index)


단어 집합의 크기: 155
{'a': 1, 'b': 2, 'c': 3, '2': 4, '그림': 5, 'convolution': 6, 'layer': 7, '1': 8, 'cnn의': 9, '크게': 10, 'fully': 11, 'connected': 12, '두': 13, 'feature를': 14, '역할을': 15, '같은': 16, '인접한': 17, '이는': 18, '이미지의': 19, '특성': 20, '특집원고': 21, '사진': 22, '기반': 23, '추천': 24, '이미지': 25, '을': 26, '반영한': 27, '것이다': 28, '구조': 29, '및': 30, '학습': 31, 'cnn은': 32, '1과': 33, '같이': 34, 'pooling': 35, '와': 36, 'layer의': 37, '부분으로': 38, '구성되어': 39, '있': 40, '다': 41, '전자는': 42, '입력된': 43, '이미지로부터': 44, '계층적': 45, '구조의': 46, '추출하는': 47, '후자는': 48, '추출된': 49, '입력받아': 50, '타겟': 51, '클래스로': 52, '분류하는': 53, '담당한다': 54, 'cnn': 55, 'layer는': 56, '아래와': 57, '가지': 58, '특징을': 59, '통해': 60, '이': 61, '미지': 62, '데이터의': 63, '특성을': 64, '반영하는': 65, '동시에': 66, '모델의': 67, '복잡': 68, '도를': 69, '단순화시킨다': 70, 'local': 71, 'connectivity': 72, '가장': 73, '일반적인': 74, '형태인': 75, 'layer와': 76, '달리': 77, '해당': 78, '필터의': 79, '크기': 80, '인': 81, 'nxn': 82, 'window': 83, '내의': 84, '뉴런들에만': 85, '연결이': 86, '되': 87, '어있다': 88, '픽셀들

In [9]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
print('훈련 데이터의 개수: %d' % len(sequences))

print(sequences)


훈련 데이터의 개수: 165
[[4, 8], [4, 8, 9], [4, 8, 9, 29], [4, 8, 9, 29, 30], [4, 8, 9, 29, 30, 31], [32, 5], [32, 5, 33], [32, 5, 33, 34], [32, 5, 33, 34, 10], [32, 5, 33, 34, 10, 6], [32, 5, 33, 34, 10, 6, 35], [32, 5, 33, 34, 10, 6, 35, 7], [36, 11], [36, 11, 12], [36, 11, 12, 37], [36, 11, 12, 37, 13], [36, 11, 12, 37, 13, 38], [36, 11, 12, 37, 13, 38, 39], [36, 11, 12, 37, 13, 38, 39, 40], [41, 42], [41, 42, 43], [41, 42, 43, 44], [41, 42, 43, 44, 45], [41, 42, 43, 44, 45, 46], [14, 47], [14, 47, 15], [14, 47, 15, 48], [14, 47, 15, 48, 49], [14, 47, 15, 48, 49, 14], [50, 51], [50, 51, 52], [50, 51, 52, 53], [50, 51, 52, 53, 15], [50, 51, 52, 53, 15, 54], [55, 56], [55, 56, 57], [55, 56, 57, 16], [55, 56, 57, 16, 13], [55, 56, 57, 16, 13, 58], [55, 56, 57, 16, 13, 58, 59], [55, 56, 57, 16, 13, 58, 59, 60], [55, 56, 57, 16, 13, 58, 59, 60, 61], [62, 63], [62, 63, 64], [62, 63, 64, 65], [62, 63, 64, 65, 66], [62, 63, 64, 65, 66, 67], [62, 63, 64, 65, 66, 67, 68], [69, 10], [69, 10, 70], [8, 

In [10]:
print(max(len(l) for l in sequences))

20


In [11]:

from keras_preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences, maxlen=6, padding='pre')

In [12]:
print(sequences)

[[  0   0   0   0   4   8]
 [  0   0   0   4   8   9]
 [  0   0   4   8   9  29]
 [  0   4   8   9  29  30]
 [  4   8   9  29  30  31]
 [  0   0   0   0  32   5]
 [  0   0   0  32   5  33]
 [  0   0  32   5  33  34]
 [  0  32   5  33  34  10]
 [ 32   5  33  34  10   6]
 [  5  33  34  10   6  35]
 [ 33  34  10   6  35   7]
 [  0   0   0   0  36  11]
 [  0   0   0  36  11  12]
 [  0   0  36  11  12  37]
 [  0  36  11  12  37  13]
 [ 36  11  12  37  13  38]
 [ 11  12  37  13  38  39]
 [ 12  37  13  38  39  40]
 [  0   0   0   0  41  42]
 [  0   0   0  41  42  43]
 [  0   0  41  42  43  44]
 [  0  41  42  43  44  45]
 [ 41  42  43  44  45  46]
 [  0   0   0   0  14  47]
 [  0   0   0  14  47  15]
 [  0   0  14  47  15  48]
 [  0  14  47  15  48  49]
 [ 14  47  15  48  49  14]
 [  0   0   0   0  50  51]
 [  0   0   0  50  51  52]
 [  0   0  50  51  52  53]
 [  0  50  51  52  53  15]
 [ 50  51  52  53  15  54]
 [  0   0   0   0  55  56]
 [  0   0   0  55  56  57]
 [  0   0  55  56  57  16]
 

In [13]:
import numpy as np
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]
# 리스트의 마지막 열을 제외하고 저장한 것은 X
# 리스트의 마지막 열만 저장한 것은 y

In [57]:
print(X)
print(y)

[[  0   0   0   0   4]
 [  0   0   0   4   8]
 [  0   0   4   8   9]
 [  0   4   8   9  29]
 [  4   8   9  29  30]
 [  0   0   0   0  32]
 [  0   0   0  32   5]
 [  0   0  32   5  33]
 [  0  32   5  33  34]
 [ 32   5  33  34  10]
 [  5  33  34  10   6]
 [ 33  34  10   6  35]
 [  0   0   0   0  36]
 [  0   0   0  36  11]
 [  0   0  36  11  12]
 [  0  36  11  12  37]
 [ 36  11  12  37  13]
 [ 11  12  37  13  38]
 [ 12  37  13  38  39]
 [  0   0   0   0  41]
 [  0   0   0  41  42]
 [  0   0  41  42  43]
 [  0  41  42  43  44]
 [ 41  42  43  44  45]
 [  0   0   0   0  14]
 [  0   0   0  14  47]
 [  0   0  14  47  15]
 [  0  14  47  15  48]
 [ 14  47  15  48  49]
 [  0   0   0   0  50]
 [  0   0   0  50  51]
 [  0   0  50  51  52]
 [  0  50  51  52  53]
 [ 50  51  52  53  15]
 [  0   0   0   0  55]
 [  0   0   0  55  56]
 [  0   0  55  56  57]
 [  0  55  56  57  16]
 [ 55  56  57  16  13]
 [ 56  57  16  13  58]
 [ 57  16  13  58  59]
 [ 16  13  58  59  60]
 [  0   0   0   0  62]
 [  0   0  

In [14]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import SimpleRNN
tf.compat.v1.enable_eager_execution()

In [59]:
from keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)
# y에 대한 원-핫 인코딩 수행
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [60]:
from keras.layers import Embedding, Dense, SimpleRNN
from keras.models import Sequential
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=5))
# y를 제거하였으므로 이제 x의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
6/6 - 1s - loss: 5.0465 - accuracy: 0.0121
Epoch 2/200
6/6 - 0s - loss: 5.0337 - accuracy: 0.0121
Epoch 3/200
6/6 - 0s - loss: 5.0235 - accuracy: 0.0182
Epoch 4/200
6/6 - 0s - loss: 5.0136 - accuracy: 0.0545
Epoch 5/200
6/6 - 0s - loss: 5.0028 - accuracy: 0.0788
Epoch 6/200
6/6 - 0s - loss: 4.9906 - accuracy: 0.0970
Epoch 7/200
6/6 - 0s - loss: 4.9760 - accuracy: 0.1091
Epoch 8/200
6/6 - 0s - loss: 4.9595 - accuracy: 0.1273
Epoch 9/200
6/6 - 0s - loss: 4.9380 - accuracy: 0.1212
Epoch 10/200
6/6 - 0s - loss: 4.9135 - accuracy: 0.1394
Epoch 11/200
6/6 - 0s - loss: 4.8837 - accuracy: 0.1515
Epoch 12/200
6/6 - 0s - loss: 4.8449 - accuracy: 0.1576
Epoch 13/200
6/6 - 0s - loss: 4.8003 - accuracy: 0.1515
Epoch 14/200
6/6 - 0s - loss: 4.7469 - accuracy: 0.1636
Epoch 15/200
6/6 - 0s - loss: 4.6882 - accuracy: 0.1758
Epoch 16/200
6/6 - 0s - loss: 4.6229 - accuracy: 0.2061
Epoch 17/200
6/6 - 0s - loss: 4.5514 - accuracy: 0.2061
Epoch 18/200
6/6 - 0s - loss: 4.4774 - accuracy: 0.2121
E

Epoch 147/200
6/6 - 0s - loss: 0.8174 - accuracy: 0.9455
Epoch 148/200
6/6 - 0s - loss: 0.8130 - accuracy: 0.9394
Epoch 149/200
6/6 - 0s - loss: 0.8003 - accuracy: 0.9455
Epoch 150/200
6/6 - 0s - loss: 0.7901 - accuracy: 0.9455
Epoch 151/200
6/6 - 0s - loss: 0.7824 - accuracy: 0.9394
Epoch 152/200
6/6 - 0s - loss: 0.7733 - accuracy: 0.9394
Epoch 153/200
6/6 - 0s - loss: 0.7776 - accuracy: 0.9576
Epoch 154/200
6/6 - 0s - loss: 0.7722 - accuracy: 0.9758
Epoch 155/200
6/6 - 0s - loss: 0.7529 - accuracy: 0.9576
Epoch 156/200
6/6 - 0s - loss: 0.7456 - accuracy: 0.9394
Epoch 157/200
6/6 - 0s - loss: 0.7276 - accuracy: 0.9515
Epoch 158/200
6/6 - 0s - loss: 0.7177 - accuracy: 0.9697
Epoch 159/200
6/6 - 0s - loss: 0.7093 - accuracy: 0.9636
Epoch 160/200
6/6 - 0s - loss: 0.7005 - accuracy: 0.9576
Epoch 161/200
6/6 - 0s - loss: 0.6941 - accuracy: 0.9515
Epoch 162/200
6/6 - 0s - loss: 0.6842 - accuracy: 0.9636
Epoch 163/200
6/6 - 0s - loss: 0.6805 - accuracy: 0.9818
Epoch 164/200
6/6 - 0s - loss: 

In [61]:
def sentence_generation(model, t, current_word, n):
    # 모델, 토크나이저, 현재 단어, 반복 횟수
    init_word = current_word
    # 처음 들어온 단어도 마지막에 출력하기 위해 저장
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
        # 입력한 X(현재 단어)에 대해서 Y를 입력하고
        # Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word
    # 전체 반복
    sentence = init_word + sentence
    return sentence

In [1]:
print(sentence_generation(model, t, '특성', 6))


NameError: name 'sentence_generation' is not defined