# 자동완성기능 구현
1. 변수 a에 다음올 단어를 예측하게끔 하면 어떨까

In [1]:
class Node:
    def __init__(self):
        self.next = {}
        self.depth=0
        self.words = set()
        self.last = False

In [4]:
class WordTrie:
    def __init__(self, words):
        self.root = Node()
        for word in words :
            self.insert(word)
    
    def insert(self, word):
        n = self.root
        for w in word:
            if w not in n.next:
                n.next[w] = Node()
                n.next[w].depth = n.depth +1
            n.words.add(word[n.depth:])
            n=n.next[w]
        n.last = True

In [5]:
class AutoComplete(WordTrie):
    def __init__(self, words):
        super().__init__(words)
        
    def suggest(self, keyword):
        n=self.root
        for k in keyword:
            if k not in n.next: return []
            n=n.next[k]
        a=[]
        if n.last: a.append(keyword)
        for word in n.words:
            a.append(keyword+word)
        return a

In [9]:
a = AutoComplete(['go','gone','guild','word','war','warrior','world'])
print(a.suggest('wo'))

['word', 'world']


# RNN(LSTM)이해하기

In [14]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM


In [21]:
#1. data 구성
x = array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
y = array([4,5,6,7])

print('x shape: ', x.shape)
print('y shape: ', y.shape)

print(x)
# print(y)
print('---x shape----')

x=x.reshape((x.shape[0], x.shape[1], 1))
print('x shape: ',x.shape)
print(x)

x shape:  (4, 3)
y shape:  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[4 5 6 7]
---x shape----
x shape:  (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


In [25]:
#2. model 구성
model = Sequential()
model.add(LSTM(10, activation='relu', input_shape=(3,1)))
model.add(Dense(5))
model.add(Dense(1))

model.summary()

#3. execute
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=100, batch_size=1)

x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 10)                480       
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 6         
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
4/4 [==============================] - 3s 4ms/step - loss: 51.5611
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 44.2149
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 35.3582
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 42.2220
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: