In [4]:
import PyPDF2
from tika import parser
from keras_preprocessing.text import Tokenizer

raw = parser.from_file('sample.pdf') # 파일 읽고

list1=[]
list1.append(raw['content']) # 파일 내용 넣고
text = " ".join(list1) # 파일 내용을 객체에서 문자열로 변환

print(text)


2021-01-18 13:41:18,076 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.24/tika-server-1.24.jar to C:\Users\qhdud\AppData\Local\Temp\tika-server.jar.
2021-01-18 13:41:32,247 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.24/tika-server-1.24.jar.md5 to C:\Users\qhdud\AppData\Local\Temp\tika-server.jar.md5.
2021-01-18 13:41:34,058 [MainThread  ] [WARNI]  Failed to see startup log message; retrying...














































DBPIA-NURIMEDIA


빅 데이터의 분석과 활용
Analysis and Utilization of Big Data

저자

(Authors)

강만모, 김상락, 박상무
 Man-Mo Kang, Sang-Rak Kim, Sang-Moo Park

출처

(Source)

정보과학회지 30(6), 2012.6, 25-32(8 pages)
Communications of the Korean Institute of Information Scientists and Engineers 30(6), 2012.6, 25-32(8 pages)

발행처

(Publisher)

한국정보과학회
KOREA INFORMATION SCIENCE SOCIETY

URL http://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE01879803

APA Style 강만모, 김상락, 박상무 (2012). 빅 데이터의 분석과 활용. 정보과학회지, 30(6), 25-32

이용정보

(Accessed)

저작권 안내

DBpia에서 제공되는 모든 저작물의 저작권은 원저작자에게 있으며, 누리미디어는 각 저작물의 내용을 보증하거나 책임을 지지 않습니다. 그리고 DBpia에서 제공되는 저작물은
DBpia와 구독계약을 체결한 기관소속 이용자 혹은 해당 저작물의 개별 구매자가 비영리적으로만 이용할 수 있습니다. 그러므로 이에 위반하여 DBpia에서 제공되는 저작물을 복제,
전송 등의 방법으로 무단 이용하는 경우 관련 법령에 따라 민, 형사상의 책임을 질 수 있습니다.

Copyright Information

Copyright of all literary works provided by DBpia belongs to the copyright holder(s)and Nurimedia does not guarantee contents of the literary work or as

In [19]:
#test for extract

list2=[]
num=0
temp=""

start=""
end=""

for i in range(len(text)):# 문장 끝까지 반복함.
    if text[i]=="\n":         
        if temp.replace(" ","")=="1.서론":
            start=temp
        if temp.replace(" ","")=="참고문헌":
            end=temp
        list2.append(temp)
        temp=""
        num+=1
    else : 
        temp+=text[i] # 문장을 만들기.


        
        
print(start,'\n',end)

1. 서 론 
 참고문헌


In [83]:
start_idx=0
end_idx=0
for i in range(len(list2)):
    if(list2[i]==start):
        start_idx=i
    if(list2[i]==end):
        end_idx=i
        break

list3=[]
for i in range(start_idx+1,end_idx):
    if list2[i]!='' and list2[i].isdigit()==False:
#         print(list2[i])
        list3.append(list2[i])

str_list3 = ''.join(list3)
str_list3 = str_list3.replace('•','')

str_list3 # 서론부터 읽은 본문 문자열 내용



'최근 IT 분야의 화두가 무엇인지 물어본다면, 빅 데이터가 대답들 중 하나일 것이다. 20년 전의 PC의 메모리, 하드디스크의 용량과 최신 PC, 노트북 사양을 비교해보면 과거에 비해 데이터가 폭발적으로 늘어났다는 것을 실감할 수 있을 것이다. 특히 스마트 단말기 및 SNS 등으로 대표되는 다양한 정보 채널의 등장과 이로 인한 정보의 생산, 유통, 보유량의 증가로 인하여 데이터가 기하급수적으로 증가하고 있다.빅데이터란 무엇인가? 빅데이터는 일반적인 데이터베이스, 소프트웨어로는 관리하기 어려운 정도의 큰 규모로서, 현재 수십 테라바이트에서 향후 페타바이트, 엑사바이트 정도 크기의 대용량 데이터를 의미하며, 최근 빅데이터는 대용량데이터의 수집, 저장, 분석, 체계화를 위한 도구, 플랫폼, 분석기법 등을 포괄하는 용어로 변화하고 있으며, 대용량데이터를 활용․분석하여 가치 있는 정보를 추출하고 생성된 지식을 바탕으로 능동적으로 대응하거나 변화를 예측하기 위한 정보화 기술을 말한다. 사실 빅 데이터에 대해서 구체적이고 정량적인 정의가 합의된 바는 없다. 세계적인 컨설팅 기관인 McKinsey지는 2011년 5월에 발간한 보고서에서[1] “빅 데이터의 정의는 기존 데이터베이스 관리 도구의 데이터 수집, 저장, 관리, 분석하는 역량을 넘어서는 데이터셋 규모로, 그 정의는 주관적이며 앞으로도 계속 변화될 것이다.” 하지만 빅데이터 중에서 가치 있는 데이터는 소수에 불과하다. 따라서 대용량 데이터를 분석하여 의미 있는 데이터를 발견하는 기술이 필요하다.본 고에서는 2장에서는 빅데이터의 요소 및 분석 기술에 대하여 알아보고 3장에서는 분석을 위한 인프라에 대하여 설명하고 4장에서는 빅데이터의 국내외 현황을 알아보고 5장은 빅데이터의 활용방안에 대하여 설명하고, 6장과 7장에서는 향후 트렌드를 알아보고 결론을 기술한다.2. 빅데이터의 요소빅데이터의 요소기술에는 미디어나 위치정보, 동영상 등을 나타내는 데이터의 크기(Volume), 실시간으로 데이터가 생성되는 데이터 입출력 속도

In [84]:
list4=[]
temp=""
for i in range(len(str_list3)):
    if str_list3[i]==".":
        list4.append(temp)
        temp=""        
    else:
        temp+=str_list3[i]
        
text = '\n'.join(list4)

text # 한국어 문장 생성


'최근 IT 분야의 화두가 무엇인지 물어본다면, 빅 데이터가 대답들 중 하나일 것이다\n 20년 전의 PC의 메모리, 하드디스크의 용량과 최신 PC, 노트북 사양을 비교해보면 과거에 비해 데이터가 폭발적으로 늘어났다는 것을 실감할 수 있을 것이다\n 특히 스마트 단말기 및 SNS 등으로 대표되는 다양한 정보 채널의 등장과 이로 인한 정보의 생산, 유통, 보유량의 증가로 인하여 데이터가 기하급수적으로 증가하고 있다\n빅데이터란 무엇인가? 빅데이터는 일반적인 데이터베이스, 소프트웨어로는 관리하기 어려운 정도의 큰 규모로서, 현재 수십 테라바이트에서 향후 페타바이트, 엑사바이트 정도 크기의 대용량 데이터를 의미하며, 최근 빅데이터는 대용량데이터의 수집, 저장, 분석, 체계화를 위한 도구, 플랫폼, 분석기법 등을 포괄하는 용어로 변화하고 있으며, 대용량데이터를 활용․분석하여 가치 있는 정보를 추출하고 생성된 지식을 바탕으로 능동적으로 대응하거나 변화를 예측하기 위한 정보화 기술을 말한다\n 사실 빅 데이터에 대해서 구체적이고 정량적인 정의가 합의된 바는 없다\n 세계적인 컨설팅 기관인 McKinsey지는 2011년 5월에 발간한 보고서에서[1] “빅 데이터의 정의는 기존 데이터베이스 관리 도구의 데이터 수집, 저장, 관리, 분석하는 역량을 넘어서는 데이터셋 규모로, 그 정의는 주관적이며 앞으로도 계속 변화될 것이다\n” 하지만 빅데이터 중에서 가치 있는 데이터는 소수에 불과하다\n 따라서 대용량 데이터를 분석하여 의미 있는 데이터를 발견하는 기술이 필요하다\n본 고에서는 2장에서는 빅데이터의 요소 및 분석 기술에 대하여 알아보고 3장에서는 분석을 위한 인프라에 대하여 설명하고 4장에서는 빅데이터의 국내외 현황을 알아보고 5장은 빅데이터의 활용방안에 대하여 설명하고, 6장과 7장에서는 향후 트렌드를 알아보고 결론을 기술한다\n2\n 빅데이터의 요소빅데이터의 요소기술에는 미디어나 위치정보, 동영상 등을 나타내는 데이터의 크기(Volume), 실시간으로 데이터가 생성되는 

In [85]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [86]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index)+1

print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 1680


In [87]:
print(t.word_index)

{'있다': 1, '데이터': 2, '및': 3, '빅데이터': 4, '수': 5, '분석': 6, '있는': 7, '위한': 8, '빅데이터의': 9, '데이터의': 10, '데이터를': 11, '등': 12, '2': 13, '것으로': 14, '소셜': 15, '하둡': 16, '1': 17, '빅데이터를': 18, '5': 19, '대한': 20, '등의': 21, '빅': 22, '것이다': 23, '를': 24, '텍스트': 25, '3': 26, '분산': 27, '관리': 28, '통해': 29, '등을': 30, '기술': 31, '그림': 32, '20': 33, '하둡은': 34, '솔루션': 35, '통한': 36, '데이터가': 37, 'pc': 38, '대용량': 39, '있으며': 40, '기술이': 41, '필요하다': 42, '분석을': 43, '활용을': 44, 'ip': 45, '117': 46, '16': 47, '225': 48, 'accessed': 49, '2020': 50, '09': 51, '19': 52, '38': 53, 'kst': 54, '분석과': 55, '새로운': 56, '마이닝': 57, '위해': 58, '관련': 59, '네트워크': 60, '할': 61, '6': 62, '4': 63, '7': 64, '업체': 65, '국내': 66, '이를': 67, '있을': 68, '데이터베이스': 69, '저장': 70, '3대': 71, '자원': 72, '등에': 73, '같이': 74, '처리': 75, '등이': 76, '기업': 77, '하는': 78, '서비스': 79, '인천대학교': 80, '같은': 81, '활용하는': 82, '것이': 83, '최근': 84, 'it': 85, '특히': 86, '다양한': 87, '정보': 88, '향후': 89, '수집': 90, '정보를': 91, '기술을': 92, '그': 93, '대하여': 94, '나타내는': 95, '실시간으로': 96, 

In [88]:
# 훈련 데이터 만들기
sequences = list()
for line in text.split('\n'): # Wn을 기준으로 문장 토큰화
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 2671


In [89]:
print(sequences)

# 아직 사용될 단어를 분리하지 않은 상태의 데이터.

[[84, 85], [84, 85, 116], [84, 85, 116, 410], [84, 85, 116, 410, 411], [84, 85, 116, 410, 411, 412], [84, 85, 116, 410, 411, 412, 22], [84, 85, 116, 410, 411, 412, 22, 37], [84, 85, 116, 410, 411, 412, 22, 37, 413], [84, 85, 116, 410, 411, 412, 22, 37, 413, 117], [84, 85, 116, 410, 411, 412, 22, 37, 413, 117, 414], [84, 85, 116, 410, 411, 412, 22, 37, 413, 117, 414, 23], [415, 416], [415, 416, 417], [415, 416, 417, 188], [415, 416, 417, 188, 418], [415, 416, 417, 188, 418, 419], [415, 416, 417, 188, 418, 419, 189], [415, 416, 417, 188, 418, 419, 189, 38], [415, 416, 417, 188, 418, 419, 189, 38, 420], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421, 422], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421, 422, 423], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421, 422, 423, 424], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421, 422, 423, 424, 37], [415, 416, 417, 188, 418, 419, 189, 38, 420, 421, 422, 423, 424, 37, 425], [415, 416, 41

In [90]:
max_len=max(len(l) for l in sequences) 
# 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
# 가장 긴 샘플의 길이로 패딩.

샘플의 최대 길이 : 142


In [91]:
print(sequences)
# 가장 긴 샘플(142) 보다 짧은 샘플들이 앞에 0을 채움.

[[   0    0    0 ...    0   84   85]
 [   0    0    0 ...   84   85  116]
 [   0    0    0 ...   85  116  410]
 ...
 [   0    0    0 ...   20 1677 1678]
 [   0    0    0 ... 1677 1678 1679]
 [   0    0    0 ... 1678 1679   23]]


In [93]:
sequences = np.array(sequences)
X = sequences[:,:-1] # 리스트마지막제외값들.
y = sequences[:,-1] # 모든 샘플의 레이블(마지막값만저장)

In [94]:
print(X)

[[   0    0    0 ...    0    0   84]
 [   0    0    0 ...    0   84   85]
 [   0    0    0 ...   84   85  116]
 ...
 [   0    0    0 ...  336   20 1677]
 [   0    0    0 ...   20 1677 1678]
 [   0    0    0 ... 1677 1678 1679]]


In [96]:
y = to_categorical(y, num_classes=vocab_size) # 원핫인코딩

In [97]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [98]:
# 모델 설계하기
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [99]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
84/84 - 4s - loss: 7.4272 - accuracy: 0.0045
Epoch 2/200
84/84 - 2s - loss: 7.2581 - accuracy: 0.0168
Epoch 3/200
84/84 - 2s - loss: 7.1075 - accuracy: 0.0139
Epoch 4/200
84/84 - 2s - loss: 7.0514 - accuracy: 0.0161
Epoch 5/200
84/84 - 2s - loss: 6.9927 - accuracy: 0.0161
Epoch 6/200
84/84 - 2s - loss: 6.8938 - accuracy: 0.0165
Epoch 7/200
84/84 - 2s - loss: 6.7844 - accuracy: 0.0206
Epoch 8/200
84/84 - 2s - loss: 6.6530 - accuracy: 0.0225
Epoch 9/200
84/84 - 2s - loss: 6.5157 - accuracy: 0.0262
Epoch 10/200
84/84 - 2s - loss: 6.3759 - accuracy: 0.0322
Epoch 11/200
84/84 - 2s - loss: 6.2314 - accuracy: 0.0431
Epoch 12/200
84/84 - 2s - loss: 6.0876 - accuracy: 0.0468
Epoch 13/200
84/84 - 2s - loss: 5.9459 - accuracy: 0.0633
Epoch 14/200
84/84 - 2s - loss: 5.8039 - accuracy: 0.0782
Epoch 15/200
84/84 - 2s - loss: 5.7946 - accuracy: 0.0734
Epoch 16/200
84/84 - 2s - loss: 5.5771 - accuracy: 0.0958
Epoch 17/200
84/84 - 2s - loss: 5.4270 - accuracy: 0.1239
Epoch 18/200
84/84 - 2s

Epoch 142/200
84/84 - 2s - loss: 0.2623 - accuracy: 0.9700
Epoch 143/200
84/84 - 2s - loss: 0.2565 - accuracy: 0.9689
Epoch 144/200
84/84 - 2s - loss: 0.2511 - accuracy: 0.9700
Epoch 145/200
84/84 - 2s - loss: 0.2461 - accuracy: 0.9697
Epoch 146/200
84/84 - 2s - loss: 0.2432 - accuracy: 0.9704
Epoch 147/200
84/84 - 2s - loss: 0.2368 - accuracy: 0.9723
Epoch 148/200
84/84 - 2s - loss: 0.2313 - accuracy: 0.9712
Epoch 149/200
84/84 - 2s - loss: 0.2269 - accuracy: 0.9719
Epoch 150/200
84/84 - 2s - loss: 0.2226 - accuracy: 0.9719
Epoch 151/200
84/84 - 2s - loss: 0.2179 - accuracy: 0.9712
Epoch 152/200
84/84 - 2s - loss: 0.2130 - accuracy: 0.9723
Epoch 153/200
84/84 - 2s - loss: 0.2092 - accuracy: 0.9719
Epoch 154/200
84/84 - 2s - loss: 0.2054 - accuracy: 0.9738
Epoch 155/200
84/84 - 2s - loss: 0.2009 - accuracy: 0.9738
Epoch 156/200
84/84 - 2s - loss: 0.1975 - accuracy: 0.9727
Epoch 157/200
84/84 - 2s - loss: 0.1949 - accuracy: 0.9734
Epoch 158/200
84/84 - 2s - loss: 0.1909 - accuracy: 0.97

In [100]:
# 문장예측이 잘되는지확인하기 위한 함수
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [106]:
print(sentence_generation(model,t,'출시한',8)) # 실패! 

출시한 등은 데이터 등의 빅데이터 측면과 지원 스트림 진행될
